stages:
  - linting
  - test
  - build
  - deploy

linting:
  stage: linting
  image: alpine
  before_script:
    - apk --no-cache add py3-pip python3-dev gcc linux-headers musl-dev libffi-dev openssl-dev git
    - pip3 install flake8 mccabe pycodestyle pyflakes
  script:
    - python3 -m flake8 --count .
  tags:
    - daedalus

run_tests:
  stage: test
  image: python:3.9
  before_script:
    - pip install -r requirements.txt
    - apt-get update
    - apt-get install ffmpeg libsm6 libxext6  -y
  script:
    - pytest -v
  tags:
    - daedalus
  only:
    - master
    - merge_requests


build-image-mr:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
    - echo $CI_PROJECT_DIR
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile ./Dockerfile --destination $CI_REGISTRY_IMAGE/web_app_dev:$CI_COMMIT_TAG
  tags:
    - daedalus
  only:
    - merge_requests


build-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
    - echo $CI_PROJECT_DIR
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile ./Dockerfile --destination $CI_REGISTRY_IMAGE/web_app:$CI_COMMIT_TAG
  tags:
    - daedalus
  only:
    - master

